/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.jeremie.javaswing;


import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author Administrateur
 */
public class TaxeFrame extends javax.swing.JFrame {

    /**
     * Creates new form TaxeFrame
     */
    public TaxeFrame() {
        initComponents();
        populateCombo();
        populateYearCombo();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        calculLabel = new javax.swing.JLabel();
        montant_Label = new javax.swing.JLabel();
        montant_TTC_Label = new javax.swing.JLabel();
        montantHT = new javax.swing.JTextField();
        calculerButton = new javax.swing.JButton();
        resultat = new javax.swing.JFormattedTextField();
        tva20RadioButton = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        fruitComboBox = new javax.swing.JComboBox<>();
        comboResultLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        anneeExpiratationLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calculLabel.setBackground(new java.awt.Color(102, 153, 255));
        calculLabel.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        calculLabel.setText("  Calcul de montant TTC");
        calculLabel.setOpaque(true);

        montant_Label.setText("Montant HT");

        montant_TTC_Label.setText("Montant TTC");

        montantHT.setToolTipText("Indiquer un montant");
        montantHT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                montantHTFocusGained(evt);
            }
        });
        montantHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montantHTActionPerformed(evt);
            }
        });

        calculerButton.setBackground(new java.awt.Color(255, 255, 153));
        calculerButton.setText("Calculer");
        calculerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculerButtonActionPerformed(evt);
            }
        });

        resultat.setToolTipText("resultat");
        resultat.setEnabled(false);
        resultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultatActionPerformed(evt);
            }
        });

        buttonGroup1.add(tva20RadioButton);
        tva20RadioButton.setText("20%");
        tva20RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tva20RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton15);
        jRadioButton15.setText("15,50%");

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("7%");

        fruitComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pommes", "Oranges", "Mangues", "Bananes" }));
        fruitComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fruitComboBoxItemStateChanged(evt);
            }
        });

        comboResultLabel.setText("jLabel1");

        anneeExpiratationLabel.setText("Année d'expiration");

        jComboBox1.setFocusCycleRoot(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anneeExpiratationLabel)
                        .addGap(37, 37, 37)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(resultat, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jRadioButton15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton7)))
                    .addComponent(calculLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(montant_Label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(montantHT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tva20RadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(montant_TTC_Label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fruitComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calculerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboResultLabel))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(calculLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(montant_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(montantHT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tva20RadioButton)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fruitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboResultLabel))
                .addGap(32, 32, 32)
                .addComponent(montant_TTC_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anneeExpiratationLabel)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void montantHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montantHTActionPerformed
         
    }//GEN-LAST:event_montantHTActionPerformed

    
    
   
    private void calculerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculerButtonActionPerformed
//Récupérer le montant hors taxe saisi
    double coutHT = 1.2* Double.valueOf(montantHT.getText());
    double result;
    double taux;
    
    if(tva20RadioButton.isSelected()){
        taux = 1.2;
    } else if (jRadioButton15.isSelected()){
        taux = 1.155;
    } else{
        taux = 1.7;
        jRadioButton7.setSelected (true);
    }
    result = taux * coutHT;
    resultat.setValue(result);
   
    montantHT.requestFocus();
    }//GEN-LAST:event_calculerButtonActionPerformed

    private void montantHTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_montantHTFocusGained
        montantHT.selectAll();
    }//GEN-LAST:event_montantHTFocusGained

    private void resultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultatActionPerformed

    private void tva20RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tva20RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tva20RadioButtonActionPerformed

    private void fruitComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fruitComboBoxItemStateChanged
        comboResultLabel.setText(fruitComboBox.getSelectedIndex() + " " + fruitComboBox.getSelectedItem());
    }//GEN-LAST:event_fruitComboBoxItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // intégrer des dates d'xpiration
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void populateCombo()  {
        
        //Pour ajout on commence par récupérer le model existant de la liste
        DefaultComboBoxModel model = (DefaultComboBoxModel)fruitComboBox.getModel();
        model.addElement("Fruit de la passion");
        model.addElement ("Kiwi");
    
        //remplacer des données d'une combo
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        model2.addElement("navet");
        model2.addElement("pomme de terre");
        model2.addElement("topinambour");
    
        //Affecter le nouveau model à la Combo
        fruitComboBox.setModel(model2);
        
             
    }
    
       private void populateYearCombo() {
           //Récupérer l'annéee en cours
         
        int currentYear = Calendar.getInstance().get(Calendar.YEAR);
        
        // Création d'un model pour la combo
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        for (int i = 0; i < 10; i++) {
            model.addElement(currentYear +i);
        }
        jComboBox1.setModel (model);
       }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaxeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaxeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaxeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaxeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaxeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anneeExpiratationLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel calculLabel;
    private javax.swing.JButton calculerButton;
    private javax.swing.JLabel comboResultLabel;
    private javax.swing.JComboBox<String> fruitComboBox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField montantHT;
    private javax.swing.JLabel montant_Label;
    private javax.swing.JLabel montant_TTC_Label;
    private javax.swing.JFormattedTextField resultat;
    private javax.swing.JRadioButton tva20RadioButton;
    // End of variables declaration//GEN-END:variables

   
        
    }
